apiVersion: v1
kind: Service
metadata:
  name: mcp-mssql-service
  namespace: adapter
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    adapter/name: mcp-mssql
    adapter/type: mcp
    azure.workload.identity/use: "false"
  type: ClusterIP
